name: Run Tests

on:
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_FILE_TEST: db/test.db
      SCHEMA: MY_CUSTOM_SCHEMA
      PORT: 8000
      JWT_EXPIRES_IN: 604800
      JWT_SECRET: jIZQBvnyeypXbA==
      NODE_ENV: test
      API_KEY: F1Zd1SkWKsrEbHdi40gcVtDC2Xc6rwbno2QpKqdUkLw
      APP_ID: 8O0xCwiRXYxPqv1l7qTH
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm run install

      - name: Run tests
        run: npm run backend:test
